name: Release on main

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write

jobs:
  filter:
    # Only run filter step for push events, not for manual triggers
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      matched: ${{ steps.filter.outputs.match }}
    steps:
      - uses: actions/checkout@v4
      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            match:
              - added|modified:
                  - '**/*.css'
                  - '**/*.html'
                  - '**/*.md'
                  - '**/*.js'
  release:
    # On push: run only if relevant files changed
    # On manual trigger: always run
    if: github.event_name == 'workflow_dispatch' || needs.filter.outputs.matched == 'true'
    needs: [filter]
    if: needs.filter.outputs.matched == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive build output
        run: |
          mkdir release-artifacts
          cp -r dist/* release-artifacts/

      - name: Get current timestamp
        id: timestamp
        run: echo "value=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/**
          tag_name: ${{ steps.timestamp.outputs.value }}
          name: Release ${{ steps.timestamp.outputs.value }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}